// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMb1ikKDb2EZnPHYm3za5l9YgczgIapuM',
    appId: '1:1007397333202:web:514937f44ee451cf1c650b',
    messagingSenderId: '1007397333202',
    projectId: 'cryptolistfirstapp',
    authDomain: 'cryptolistfirstapp.firebaseapp.com',
    storageBucket: 'cryptolistfirstapp.appspot.com',
    measurementId: 'G-XJDW4TGQVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALF5-bxGIhw7khaFltW-dXLwgL2lzWLto',
    appId: '1:1007397333202:android:9fae8da6f2b73dcb1c650b',
    messagingSenderId: '1007397333202',
    projectId: 'cryptolistfirstapp',
    storageBucket: 'cryptolistfirstapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNfl6Sg6zUFmFVrKtmLz4-uhy20J4c44w',
    appId: '1:1007397333202:ios:d5cdcc7b701232f71c650b',
    messagingSenderId: '1007397333202',
    projectId: 'cryptolistfirstapp',
    storageBucket: 'cryptolistfirstapp.appspot.com',
    iosBundleId: 'com.gqcrypto.cryptoListFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNfl6Sg6zUFmFVrKtmLz4-uhy20J4c44w',
    appId: '1:1007397333202:ios:73baf81dbca9af7c1c650b',
    messagingSenderId: '1007397333202',
    projectId: 'cryptolistfirstapp',
    storageBucket: 'cryptolistfirstapp.appspot.com',
    iosBundleId: 'com.gqcrypto.cryptoListFirstApp.RunnerTests',
  );
}
